# SPDX-FileCopyrightText: 2023 Vladimir Rusinov
#
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-bugbear==22.12.6
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
-   repo: local
    hooks:
    # TODO: split into native hooks
    -   id: presubmit-sh
        name: presubmit-sh
        entry: bash presubmit.sh
        language: system
        always_run: true
-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/crate-ci/typos
    rev: v1.13.6
    hooks:
      - id: typos
