# SPDX-FileCopyrightText: 2023-2025 Vladimir Rusinov
# SPDX-License-Identifier: Apache-2.0
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.2.6
          - wemake-python-styleguide==0.19.2
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/crate-ci/typos
    rev: v1.26.0
    hooks:
      - id: typos
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.9.3'
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: ["--force-exclude"]
      - id: ruff-format
  - repo: https://github.com/golangci/golangci-lint
    rev: "v1.63.4"
    hooks:
      - id: golangci-lint
  - repo: https://github.com/fsfe/reuse-tool
    rev: "v5.0.2"
    hooks:
      - id: reuse
  - repo: https://github.com/cpplint/cpplint
    rev: "2.0.0"
    hooks:
      - id: cpplint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.12.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.3
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.7'
    hooks:
      - id: clang-format
