# SPDX-FileCopyrightText: 2022 Vladimir Rusinov
# SPDX-License-Identifier: Apache-2.0
[package]
name = "array_manipulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
